### ISSUE TITLE
Morning session: peer-to-peer code reviews by Alusine Jalloh, Peter Njugumna

### ISSUE THREAD

**Issue by Alusp** [binhussen/awesome-books#6]
#### Acknowledgment
- The Project is really nice,
- The refactor approach is really nice
#### Improvment
-  we suggest you add a notification on every added event
- We also suggest that you position the footer at the bottom.

**Comment by binhussen** [comment]
Thank you @Alusp and @AzizRAA for your feedback, I have updated the changes as requested and made the fixes we discussed [Link](https://github.com/binhussen/awesome-books/) here
